[package]
name = "literate-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.3", features = ["http2"] }
pulldown-cmark = "0.9.2"
syntect = "5.0.0"
